FROM golang:1.21-alpine AS build-stage

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /pow_client cmd/client/main.go

FROM scratch AS build-release-stage

WORKDIR /

COPY --from=build-stage /pow_client /pow_client

ENTRYPOINT ["/pow_client"]