FROM golang:1.21-alpine AS build-stage

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /pow_server cmd/server/main.go

FROM scratch AS build-release-stage

WORKDIR /

COPY --from=build-stage /pow_server /pow_server

ENTRYPOINT ["/pow_server"]