// Code generated by mockery v2.20.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// RandomDataGetter is an autogenerated mock type for the RandomDataGetter type
type RandomDataGetter struct {
	mock.Mock
}

// GetRandomDataBytes provides a mock function with given fields:
func (_m *RandomDataGetter) GetRandomDataBytes() ([]byte, error) {
	ret := _m.Called()

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]byte, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewRandomDataGetter interface {
	mock.TestingT
	Cleanup(func())
}

// NewRandomDataGetter creates a new instance of RandomDataGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRandomDataGetter(t mockConstructorTestingTNewRandomDataGetter) *RandomDataGetter {
	mock := &RandomDataGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
